// clang-format off
#if XOP_CUDA_ARCHS==90
#include "xop/ops_impl/gemm_normal/gemm_sm90_impl.h"

namespace xop {
using namespace cutlass;
using ME = UnifiedMetaEnum;

static int search_space_gemmsm90 = []() {
  GemmConfigRegister& ins = GemmConfigRegister::instance();
  ins.add({0,(int16_t)ME::GemmNormal,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmSm90Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,cutlass::gemm::KernelTmaWarpSpecializedPingpong,cutlass::epilogue::TmaWarpSpecialized,cutlass::gemm::PersistentScheduler>();});
  ins.add({1,(int16_t)ME::GemmNormal,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmSm90Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,cutlass::gemm::KernelTmaWarpSpecializedCooperative,cutlass::epilogue::TmaWarpSpecializedCooperative,cutlass::gemm::PersistentScheduler>();});
  ins.add({2,(int16_t)ME::GemmNormal,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmSm90Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,cutlass::gemm::KernelTmaWarpSpecializedCooperative,cutlass::epilogue::TmaWarpSpecializedCooperative,cutlass::gemm::StreamKScheduler>();});
  ins.add({3,(int16_t)ME::GemmNormal,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmSm90Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,cutlass::gemm::KernelTmaWarpSpecialized,cutlass::epilogue::TmaWarpSpecialized,cutlass::gemm::PersistentScheduler>();});
  ins.add({4,(int16_t)ME::GemmNormal,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmSm90Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,cutlass::gemm::KernelTmaWarpSpecializedPingpong,cutlass::epilogue::TmaWarpSpecialized,cutlass::gemm::PersistentScheduler>();});
  ins.add({5,(int16_t)ME::GemmNormal,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmSm90Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,cutlass::gemm::KernelTmaWarpSpecializedCooperative,cutlass::epilogue::TmaWarpSpecializedCooperative,cutlass::gemm::PersistentScheduler>();});
  ins.add({6,(int16_t)ME::GemmNormal,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmSm90Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,cutlass::gemm::KernelTmaWarpSpecializedCooperative,cutlass::epilogue::TmaWarpSpecializedCooperative,cutlass::gemm::StreamKScheduler>();});
  ins.add({7,(int16_t)ME::GemmNormal,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmSm90Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,cutlass::gemm::KernelTmaWarpSpecialized,cutlass::epilogue::TmaWarpSpecialized,cutlass::gemm::PersistentScheduler>();});
  ins.add({8,(int16_t)ME::GemmNormal,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmSm90Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cute::Shape<cute::_128,cute::_128,cute::_64>,cute::Shape<cute::_1,cute::_2,cute::_1>,cutlass::gemm::KernelTmaWarpSpecializedPingpong,cutlass::epilogue::TmaWarpSpecialized,cutlass::gemm::PersistentScheduler>();});
  ins.add({9,(int16_t)ME::GemmNormal,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmSm90Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cute::Shape<cute::_128,cute::_128,cute::_64>,cute::Shape<cute::_1,cute::_2,cute::_1>,cutlass::gemm::KernelTmaWarpSpecializedCooperative,cutlass::epilogue::TmaWarpSpecializedCooperative,cutlass::gemm::PersistentScheduler>();});
  ins.add({10,(int16_t)ME::GemmNormal,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmSm90Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cute::Shape<cute::_128,cute::_128,cute::_64>,cute::Shape<cute::_1,cute::_2,cute::_1>,cutlass::gemm::KernelTmaWarpSpecializedCooperative,cutlass::epilogue::TmaWarpSpecializedCooperative,cutlass::gemm::StreamKScheduler>();});
  ins.add({11,(int16_t)ME::GemmNormal,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmSm90Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cute::Shape<cute::_128,cute::_128,cute::_64>,cute::Shape<cute::_1,cute::_2,cute::_1>,cutlass::gemm::KernelTmaWarpSpecialized,cutlass::epilogue::TmaWarpSpecialized,cutlass::gemm::PersistentScheduler>();});
  ins.add({12,(int16_t)ME::GemmNormal,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmSm90Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cute::Shape<cute::_128,cute::_128,cute::_64>,cute::Shape<cute::_2,cute::_1,cute::_1>,cutlass::gemm::KernelTmaWarpSpecializedPingpong,cutlass::epilogue::TmaWarpSpecialized,cutlass::gemm::PersistentScheduler>();});
  ins.add({13,(int16_t)ME::GemmNormal,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmSm90Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cute::Shape<cute::_128,cute::_128,cute::_64>,cute::Shape<cute::_2,cute::_1,cute::_1>,cutlass::gemm::KernelTmaWarpSpecializedCooperative,cutlass::epilogue::TmaWarpSpecializedCooperative,cutlass::gemm::PersistentScheduler>();});
  ins.add({14,(int16_t)ME::GemmNormal,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmSm90Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cute::Shape<cute::_128,cute::_128,cute::_64>,cute::Shape<cute::_2,cute::_1,cute::_1>,cutlass::gemm::KernelTmaWarpSpecializedCooperative,cutlass::epilogue::TmaWarpSpecializedCooperative,cutlass::gemm::StreamKScheduler>();});
  ins.add({15,(int16_t)ME::GemmNormal,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmSm90Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cute::Shape<cute::_128,cute::_128,cute::_64>,cute::Shape<cute::_2,cute::_1,cute::_1>,cutlass::gemm::KernelTmaWarpSpecialized,cutlass::epilogue::TmaWarpSpecialized,cutlass::gemm::PersistentScheduler>();});
  return 0;
}();
}
#endif // #if XOP_CUDA_ARCHS==90
// clang-format on