// clang-format off
#include "ctlop/ops_impl/gemm_normal/gemm_v3_blockscale_fp8_impl.h"

namespace ctlop {
using namespace cutlass;
using ME = UnifiedMetaEnum;

static int search_space_gemmbolckscalefp8 = []() {
  GemmConfigRegister& ins = GemmConfigRegister::instance();
  ins.add({0,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,gemm::kernel::detail::RasterOrderOptions::Heuristic,2>();});
  ins.add({1,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,gemm::kernel::detail::RasterOrderOptions::Heuristic,4>();});
  ins.add({2,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,gemm::kernel::detail::RasterOrderOptions::Heuristic,8>();});
  ins.add({3,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,gemm::kernel::detail::RasterOrderOptions::AlongM,2>();});
  ins.add({4,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,gemm::kernel::detail::RasterOrderOptions::AlongM,4>();});
  ins.add({5,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,gemm::kernel::detail::RasterOrderOptions::AlongM,8>();});
  ins.add({6,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,gemm::kernel::detail::RasterOrderOptions::AlongN,2>();});
  ins.add({7,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,gemm::kernel::detail::RasterOrderOptions::AlongN,4>();});
  ins.add({8,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,gemm::kernel::detail::RasterOrderOptions::AlongN,8>();});
  ins.add({9,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,gemm::kernel::detail::RasterOrderOptions::Heuristic,2>();});
  ins.add({10,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,gemm::kernel::detail::RasterOrderOptions::Heuristic,4>();});
  ins.add({11,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,gemm::kernel::detail::RasterOrderOptions::Heuristic,8>();});
  ins.add({12,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,gemm::kernel::detail::RasterOrderOptions::AlongM,2>();});
  ins.add({13,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,gemm::kernel::detail::RasterOrderOptions::AlongM,4>();});
  ins.add({14,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,gemm::kernel::detail::RasterOrderOptions::AlongM,8>();});
  ins.add({15,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,gemm::kernel::detail::RasterOrderOptions::AlongN,2>();});
  ins.add({16,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,gemm::kernel::detail::RasterOrderOptions::AlongN,4>();});
  ins.add({17,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,gemm::kernel::detail::RasterOrderOptions::AlongN,8>();});
  ins.add({18,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,gemm::kernel::detail::RasterOrderOptions::Heuristic,2>();});
  ins.add({19,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,gemm::kernel::detail::RasterOrderOptions::Heuristic,4>();});
  ins.add({20,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,gemm::kernel::detail::RasterOrderOptions::Heuristic,8>();});
  ins.add({21,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,gemm::kernel::detail::RasterOrderOptions::AlongM,2>();});
  ins.add({22,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,gemm::kernel::detail::RasterOrderOptions::AlongM,4>();});
  ins.add({23,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,gemm::kernel::detail::RasterOrderOptions::AlongM,8>();});
  ins.add({24,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,gemm::kernel::detail::RasterOrderOptions::AlongN,2>();});
  ins.add({25,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,gemm::kernel::detail::RasterOrderOptions::AlongN,4>();});
  ins.add({26,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,gemm::kernel::detail::RasterOrderOptions::AlongN,8>();});
  ins.add({27,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,gemm::kernel::detail::RasterOrderOptions::Heuristic,2>();});
  ins.add({28,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,gemm::kernel::detail::RasterOrderOptions::Heuristic,4>();});
  ins.add({29,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,gemm::kernel::detail::RasterOrderOptions::Heuristic,8>();});
  ins.add({30,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,gemm::kernel::detail::RasterOrderOptions::AlongM,2>();});
  ins.add({31,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,gemm::kernel::detail::RasterOrderOptions::AlongM,4>();});
  ins.add({32,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,gemm::kernel::detail::RasterOrderOptions::AlongM,8>();});
  ins.add({33,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,gemm::kernel::detail::RasterOrderOptions::AlongN,2>();});
  ins.add({34,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,gemm::kernel::detail::RasterOrderOptions::AlongN,4>();});
  ins.add({35,(int8_t)ME::GemmBolckScaleFp8,(int8_t)ME::E4M3, (int8_t)ME::E4M3, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,gemm::kernel::detail::RasterOrderOptions::AlongN,8>();});
  return 0;
}();
}// clang-format on