// clang-format off
#if XOP_CUDA_ARCHS==90
#include "xop/ops_impl/gemm_normal/gemm_blockscale_fp8_sm90_impl.h"

namespace xop {
using namespace cutlass;
using ME = UnifiedMetaEnum;

static int search_space_gemmblockscalefp8sm90 = []() {
  GemmConfigRegister& ins = GemmConfigRegister::instance();
  ins.add({0,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,xop::RasterOrderOptions::Heuristic,2>();});
  ins.add({1,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,xop::RasterOrderOptions::Heuristic,4>();});
  // ins.add({2,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,xop::RasterOrderOptions::Heuristic,8>();});
  // ins.add({3,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,xop::RasterOrderOptions::AlongM,2>();});
  // ins.add({4,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,xop::RasterOrderOptions::AlongM,4>();});
  // ins.add({5,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,xop::RasterOrderOptions::AlongM,8>();});
  // ins.add({6,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,xop::RasterOrderOptions::AlongN,2>();});
  // ins.add({7,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,xop::RasterOrderOptions::AlongN,4>();});
  // ins.add({8,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,xop::RasterOrderOptions::AlongN,8>();});
  // ins.add({9,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,xop::RasterOrderOptions::Heuristic,2>();});
  // ins.add({10,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,xop::RasterOrderOptions::Heuristic,4>();});
  // ins.add({11,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,xop::RasterOrderOptions::Heuristic,8>();});
  // ins.add({12,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,xop::RasterOrderOptions::AlongM,2>();});
  // ins.add({13,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,xop::RasterOrderOptions::AlongM,4>();});
  // ins.add({14,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,xop::RasterOrderOptions::AlongM,8>();});
  // ins.add({15,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,xop::RasterOrderOptions::AlongN,2>();});
  // ins.add({16,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,xop::RasterOrderOptions::AlongN,4>();});
  // ins.add({17,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::PersistentScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,xop::RasterOrderOptions::AlongN,8>();});
  // ins.add({18,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,xop::RasterOrderOptions::Heuristic,2>();});
  // ins.add({19,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,xop::RasterOrderOptions::Heuristic,4>();});
  // ins.add({20,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,xop::RasterOrderOptions::Heuristic,8>();});
  // ins.add({21,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,xop::RasterOrderOptions::AlongM,2>();});
  // ins.add({22,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,xop::RasterOrderOptions::AlongM,4>();});
  // ins.add({23,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,xop::RasterOrderOptions::AlongM,8>();});
  // ins.add({24,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,xop::RasterOrderOptions::AlongN,2>();});
  // ins.add({25,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,xop::RasterOrderOptions::AlongN,4>();});
  // ins.add({26,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_2,cute::_1>,xop::RasterOrderOptions::AlongN,8>();});
  // ins.add({27,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,xop::RasterOrderOptions::Heuristic,2>();});
  // ins.add({28,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,xop::RasterOrderOptions::Heuristic,4>();});
  // ins.add({29,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,xop::RasterOrderOptions::Heuristic,8>();});
  // ins.add({30,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,xop::RasterOrderOptions::AlongM,2>();});
  // ins.add({31,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,xop::RasterOrderOptions::AlongM,4>();});
  // ins.add({32,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,xop::RasterOrderOptions::AlongM,8>();});
  // ins.add({33,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,xop::RasterOrderOptions::AlongN,2>();});
  // ins.add({34,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,xop::RasterOrderOptions::AlongN,4>();});
  // ins.add({35,(int16_t)ME::GemmBlockScaleFp8,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm90}, /*op*/[]() { return new GemmBlockScaleFp8Sm90Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm90,/*hparam*/cutlass::gemm::StreamKScheduler,cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_2,cute::_1,cute::_1>,xop::RasterOrderOptions::AlongN,8>();});
  return 0;
}();
}
#endif // #if XOP_CUDA_ARCHS==90
// clang-format on