// clang-format off
#include "ctlop/ops_impl/gemm_normal/gemm_v2_simt_impl.h"

namespace ctlop {
using namespace cutlass;
using ME = UnifiedMetaEnum;

static int search_space_gemmnormalsimt = []() {
  GemmConfigRegister& ins = GemmConfigRegister::instance();
  ins.add({0,(int8_t)ME::GemmNormalSimt,(int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm80}, /*op*/[]() { return new GemmPureV2SimtImpl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, cutlass::layout::RowMajor, layout::ColumnMajor, layout::RowMajor, cutlass::arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<64,64,4>,cutlass::gemm::GemmShape<32,16,4>,gemm::threadblock::GemmIdentityThreadblockSwizzle<>,3,1>();});
  ins.add({1,(int8_t)ME::GemmNormalSimt,(int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm80}, /*op*/[]() { return new GemmPureV2SimtImpl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, cutlass::layout::RowMajor, layout::ColumnMajor, layout::RowMajor, cutlass::arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<64,64,4>,cutlass::gemm::GemmShape<32,16,4>,gemm::threadblock::GemmIdentityThreadblockSwizzle<>,3,2>();});
  ins.add({2,(int8_t)ME::GemmNormalSimt,(int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm80}, /*op*/[]() { return new GemmPureV2SimtImpl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, cutlass::layout::RowMajor, layout::ColumnMajor, layout::RowMajor, cutlass::arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<64,64,4>,cutlass::gemm::GemmShape<32,16,4>,gemm::threadblock::GemmIdentityThreadblockSwizzle<>,4,1>();});
  ins.add({3,(int8_t)ME::GemmNormalSimt,(int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm80}, /*op*/[]() { return new GemmPureV2SimtImpl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, cutlass::layout::RowMajor, layout::ColumnMajor, layout::RowMajor, cutlass::arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<64,64,4>,cutlass::gemm::GemmShape<32,16,4>,gemm::threadblock::GemmIdentityThreadblockSwizzle<>,4,2>();});
  ins.add({4,(int8_t)ME::GemmNormalSimt,(int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm80}, /*op*/[]() { return new GemmPureV2SimtImpl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, cutlass::layout::RowMajor, layout::ColumnMajor, layout::RowMajor, cutlass::arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<64,64,4>,cutlass::gemm::GemmShape<32,16,4>,gemm::threadblock::ThreadblockSwizzleStreamK,3,1>();});
  ins.add({5,(int8_t)ME::GemmNormalSimt,(int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm80}, /*op*/[]() { return new GemmPureV2SimtImpl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, cutlass::layout::RowMajor, layout::ColumnMajor, layout::RowMajor, cutlass::arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<64,64,4>,cutlass::gemm::GemmShape<32,16,4>,gemm::threadblock::ThreadblockSwizzleStreamK,3,2>();});
  ins.add({6,(int8_t)ME::GemmNormalSimt,(int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm80}, /*op*/[]() { return new GemmPureV2SimtImpl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, cutlass::layout::RowMajor, layout::ColumnMajor, layout::RowMajor, cutlass::arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<64,64,4>,cutlass::gemm::GemmShape<32,16,4>,gemm::threadblock::ThreadblockSwizzleStreamK,4,1>();});
  ins.add({7,(int8_t)ME::GemmNormalSimt,(int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm80}, /*op*/[]() { return new GemmPureV2SimtImpl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, cutlass::layout::RowMajor, layout::ColumnMajor, layout::RowMajor, cutlass::arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<64,64,4>,cutlass::gemm::GemmShape<32,16,4>,gemm::threadblock::ThreadblockSwizzleStreamK,4,2>();});
  ins.add({8,(int8_t)ME::GemmNormalSimt,(int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm80}, /*op*/[]() { return new GemmPureV2SimtImpl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, cutlass::layout::RowMajor, layout::ColumnMajor, layout::RowMajor, cutlass::arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<32,32,4>,cutlass::gemm::GemmShape<16,16,4>,gemm::threadblock::GemmIdentityThreadblockSwizzle<>,3,1>();});
  ins.add({9,(int8_t)ME::GemmNormalSimt,(int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm80}, /*op*/[]() { return new GemmPureV2SimtImpl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, cutlass::layout::RowMajor, layout::ColumnMajor, layout::RowMajor, cutlass::arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<32,32,4>,cutlass::gemm::GemmShape<16,16,4>,gemm::threadblock::GemmIdentityThreadblockSwizzle<>,3,2>();});
  ins.add({10,(int8_t)ME::GemmNormalSimt,(int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm80}, /*op*/[]() { return new GemmPureV2SimtImpl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, cutlass::layout::RowMajor, layout::ColumnMajor, layout::RowMajor, cutlass::arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<32,32,4>,cutlass::gemm::GemmShape<16,16,4>,gemm::threadblock::GemmIdentityThreadblockSwizzle<>,4,1>();});
  ins.add({11,(int8_t)ME::GemmNormalSimt,(int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm80}, /*op*/[]() { return new GemmPureV2SimtImpl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, cutlass::layout::RowMajor, layout::ColumnMajor, layout::RowMajor, cutlass::arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<32,32,4>,cutlass::gemm::GemmShape<16,16,4>,gemm::threadblock::GemmIdentityThreadblockSwizzle<>,4,2>();});
  ins.add({12,(int8_t)ME::GemmNormalSimt,(int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm80}, /*op*/[]() { return new GemmPureV2SimtImpl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, cutlass::layout::RowMajor, layout::ColumnMajor, layout::RowMajor, cutlass::arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<32,32,4>,cutlass::gemm::GemmShape<16,16,4>,gemm::threadblock::ThreadblockSwizzleStreamK,3,1>();});
  ins.add({13,(int8_t)ME::GemmNormalSimt,(int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm80}, /*op*/[]() { return new GemmPureV2SimtImpl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, cutlass::layout::RowMajor, layout::ColumnMajor, layout::RowMajor, cutlass::arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<32,32,4>,cutlass::gemm::GemmShape<16,16,4>,gemm::threadblock::ThreadblockSwizzleStreamK,3,2>();});
  ins.add({14,(int8_t)ME::GemmNormalSimt,(int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm80}, /*op*/[]() { return new GemmPureV2SimtImpl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, cutlass::layout::RowMajor, layout::ColumnMajor, layout::RowMajor, cutlass::arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<32,32,4>,cutlass::gemm::GemmShape<16,16,4>,gemm::threadblock::ThreadblockSwizzleStreamK,4,1>();});
  ins.add({15,(int8_t)ME::GemmNormalSimt,(int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm80}, /*op*/[]() { return new GemmPureV2SimtImpl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, cutlass::layout::RowMajor, layout::ColumnMajor, layout::RowMajor, cutlass::arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<32,32,4>,cutlass::gemm::GemmShape<16,16,4>,gemm::threadblock::ThreadblockSwizzleStreamK,4,2>();});
  ins.add({16,(int8_t)ME::GemmNormalSimt,(int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm80}, /*op*/[]() { return new GemmPureV2SimtImpl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, cutlass::layout::RowMajor, layout::ColumnMajor, layout::RowMajor, cutlass::arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<16,32,4>,cutlass::gemm::GemmShape<8,16,4>,gemm::threadblock::GemmIdentityThreadblockSwizzle<>,3,1>();});
  ins.add({17,(int8_t)ME::GemmNormalSimt,(int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm80}, /*op*/[]() { return new GemmPureV2SimtImpl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, cutlass::layout::RowMajor, layout::ColumnMajor, layout::RowMajor, cutlass::arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<16,32,4>,cutlass::gemm::GemmShape<8,16,4>,gemm::threadblock::GemmIdentityThreadblockSwizzle<>,3,2>();});
  ins.add({18,(int8_t)ME::GemmNormalSimt,(int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm80}, /*op*/[]() { return new GemmPureV2SimtImpl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, cutlass::layout::RowMajor, layout::ColumnMajor, layout::RowMajor, cutlass::arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<16,32,4>,cutlass::gemm::GemmShape<8,16,4>,gemm::threadblock::GemmIdentityThreadblockSwizzle<>,4,1>();});
  ins.add({19,(int8_t)ME::GemmNormalSimt,(int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm80}, /*op*/[]() { return new GemmPureV2SimtImpl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, cutlass::layout::RowMajor, layout::ColumnMajor, layout::RowMajor, cutlass::arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<16,32,4>,cutlass::gemm::GemmShape<8,16,4>,gemm::threadblock::GemmIdentityThreadblockSwizzle<>,4,2>();});
  ins.add({20,(int8_t)ME::GemmNormalSimt,(int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm80}, /*op*/[]() { return new GemmPureV2SimtImpl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, cutlass::layout::RowMajor, layout::ColumnMajor, layout::RowMajor, cutlass::arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<16,32,4>,cutlass::gemm::GemmShape<8,16,4>,gemm::threadblock::ThreadblockSwizzleStreamK,3,1>();});
  ins.add({21,(int8_t)ME::GemmNormalSimt,(int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm80}, /*op*/[]() { return new GemmPureV2SimtImpl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, cutlass::layout::RowMajor, layout::ColumnMajor, layout::RowMajor, cutlass::arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<16,32,4>,cutlass::gemm::GemmShape<8,16,4>,gemm::threadblock::ThreadblockSwizzleStreamK,3,2>();});
  ins.add({22,(int8_t)ME::GemmNormalSimt,(int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm80}, /*op*/[]() { return new GemmPureV2SimtImpl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, cutlass::layout::RowMajor, layout::ColumnMajor, layout::RowMajor, cutlass::arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<16,32,4>,cutlass::gemm::GemmShape<8,16,4>,gemm::threadblock::ThreadblockSwizzleStreamK,4,1>();});
  ins.add({23,(int8_t)ME::GemmNormalSimt,(int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::BF16, (int8_t)ME::FP32, (int8_t)ME::RCR, (int8_t)ME::Sm80}, /*op*/[]() { return new GemmPureV2SimtImpl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, cutlass::layout::RowMajor, layout::ColumnMajor, layout::RowMajor, cutlass::arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<16,32,4>,cutlass::gemm::GemmShape<8,16,4>,gemm::threadblock::ThreadblockSwizzleStreamK,4,2>();});
  return 0;
}();
}// clang-format on