// clang-format off
#if XOP_CUDA_ARCHS==120
#include "xop/ops_impl/gemm_normal/gemm_blockscale_fp8_sm120_impl.h"

namespace xop {
using namespace cutlass;
using ME = UnifiedMetaEnum;

static int search_space_gemmblockscalefp8sm120 = []() {
  GemmConfigRegister& ins = GemmConfigRegister::instance();
  ins.add({0,(int16_t)ME::GemmBlockScaleFp8Sm120,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm120}, /*op*/[]() { return new GemmBlockScaleFp8Sm120Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm120,/*hparam*/cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_1,cute::_1>,cutlass::gemm::KernelTmaWarpSpecializedPingpongFP8BlockScaledAccum,cutlass::epilogue::TmaWarpSpecialized,cutlass::gemm::PersistentScheduler,xop::RasterOrderOptions::Heuristic,8>();});
  ins.add({1,(int16_t)ME::GemmBlockScaleFp8Sm120,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm120}, /*op*/[]() { return new GemmBlockScaleFp8Sm120Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm120,/*hparam*/cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_1,cute::_1>,cutlass::gemm::KernelTmaWarpSpecializedPingpongFP8BlockScaledAccum,cutlass::epilogue::TmaWarpSpecialized,cutlass::gemm::PersistentScheduler,xop::RasterOrderOptions::AlongM,8>();});
  ins.add({2,(int16_t)ME::GemmBlockScaleFp8Sm120,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm120}, /*op*/[]() { return new GemmBlockScaleFp8Sm120Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm120,/*hparam*/cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_1,cute::_1>,cutlass::gemm::KernelTmaWarpSpecializedPingpongFP8BlockScaledAccum,cutlass::epilogue::TmaWarpSpecialized,cutlass::gemm::PersistentScheduler,xop::RasterOrderOptions::AlongN,8>();});
  ins.add({3,(int16_t)ME::GemmBlockScaleFp8Sm120,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm120}, /*op*/[]() { return new GemmBlockScaleFp8Sm120Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm120,/*hparam*/cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_1,cute::_1>,cutlass::gemm::KernelTmaWarpSpecializedCooperativeFP8BlockScaledAccum,cutlass::epilogue::TmaWarpSpecializedCooperative,cutlass::gemm::PersistentScheduler,xop::RasterOrderOptions::Heuristic,8>();});
  ins.add({4,(int16_t)ME::GemmBlockScaleFp8Sm120,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm120}, /*op*/[]() { return new GemmBlockScaleFp8Sm120Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm120,/*hparam*/cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_1,cute::_1>,cutlass::gemm::KernelTmaWarpSpecializedCooperativeFP8BlockScaledAccum,cutlass::epilogue::TmaWarpSpecializedCooperative,cutlass::gemm::PersistentScheduler,xop::RasterOrderOptions::AlongM,8>();});
  ins.add({5,(int16_t)ME::GemmBlockScaleFp8Sm120,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm120}, /*op*/[]() { return new GemmBlockScaleFp8Sm120Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm120,/*hparam*/cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_1,cute::_1>,cutlass::gemm::KernelTmaWarpSpecializedCooperativeFP8BlockScaledAccum,cutlass::epilogue::TmaWarpSpecializedCooperative,cutlass::gemm::PersistentScheduler,xop::RasterOrderOptions::AlongN,8>();});
  ins.add({6,(int16_t)ME::GemmBlockScaleFp8Sm120,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm120}, /*op*/[]() { return new GemmBlockScaleFp8Sm120Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm120,/*hparam*/cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_1,cute::_1>,cutlass::gemm::KernelTmaWarpSpecializedCooperativeFP8BlockScaledAccum,cutlass::epilogue::TmaWarpSpecializedCooperative,cutlass::gemm::StreamKScheduler,xop::RasterOrderOptions::Heuristic,8>();});
  ins.add({7,(int16_t)ME::GemmBlockScaleFp8Sm120,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm120}, /*op*/[]() { return new GemmBlockScaleFp8Sm120Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm120,/*hparam*/cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_1,cute::_1>,cutlass::gemm::KernelTmaWarpSpecializedCooperativeFP8BlockScaledAccum,cutlass::epilogue::TmaWarpSpecializedCooperative,cutlass::gemm::StreamKScheduler,xop::RasterOrderOptions::AlongM,8>();});
  ins.add({8,(int16_t)ME::GemmBlockScaleFp8Sm120,(int16_t)ME::E4M3, (int16_t)ME::E4M3, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm120}, /*op*/[]() { return new GemmBlockScaleFp8Sm120Impl</*meta*/cutlass::float_e4m3_t, cutlass::float_e4m3_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm120,/*hparam*/cute::Shape<cute::_128,cute::_128,cute::_128>,cute::Shape<cute::_1,cute::_1,cute::_1>,cutlass::gemm::KernelTmaWarpSpecializedCooperativeFP8BlockScaledAccum,cutlass::epilogue::TmaWarpSpecializedCooperative,cutlass::gemm::StreamKScheduler,xop::RasterOrderOptions::AlongN,8>();});
  return 0;
}();
}
#endif // #if XOP_CUDA_ARCHS==120
// clang-format on