// clang-format off
#if XOP_CUDA_ARCHS==80 || XOP_CUDA_ARCHS==86 || XOP_CUDA_ARCHS==89
#include "xop/ops_impl/gemm_normal/gemm_simt_sm80_impl.h"

namespace xop {
using namespace cutlass;
using ME = UnifiedMetaEnum;

static int search_space_gemmsimtsm80 = []() {
  GemmConfigRegister& ins = GemmConfigRegister::instance();
  ins.add({0,(int16_t)ME::GemmNormalSimt,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm80}, /*op*/[]() { return new GemmSimtSm80Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<64,64,4>,cutlass::gemm::GemmShape<32,16,4>,gemm::threadblock::GemmIdentityThreadblockSwizzle<>,3,1>();});
  // ins.add({1,(int16_t)ME::GemmNormalSimt,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm80}, /*op*/[]() { return new GemmSimtSm80Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<64,64,4>,cutlass::gemm::GemmShape<32,16,4>,gemm::threadblock::GemmIdentityThreadblockSwizzle<>,3,2>();});
  // ins.add({2,(int16_t)ME::GemmNormalSimt,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm80}, /*op*/[]() { return new GemmSimtSm80Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<64,64,4>,cutlass::gemm::GemmShape<32,16,4>,gemm::threadblock::GemmIdentityThreadblockSwizzle<>,4,1>();});
  // ins.add({3,(int16_t)ME::GemmNormalSimt,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm80}, /*op*/[]() { return new GemmSimtSm80Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<64,64,4>,cutlass::gemm::GemmShape<32,16,4>,gemm::threadblock::GemmIdentityThreadblockSwizzle<>,4,2>();});
  // ins.add({4,(int16_t)ME::GemmNormalSimt,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm80}, /*op*/[]() { return new GemmSimtSm80Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<64,64,4>,cutlass::gemm::GemmShape<32,16,4>,gemm::threadblock::ThreadblockSwizzleStreamK,3,1>();});
  // ins.add({5,(int16_t)ME::GemmNormalSimt,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm80}, /*op*/[]() { return new GemmSimtSm80Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<64,64,4>,cutlass::gemm::GemmShape<32,16,4>,gemm::threadblock::ThreadblockSwizzleStreamK,3,2>();});
  // ins.add({6,(int16_t)ME::GemmNormalSimt,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm80}, /*op*/[]() { return new GemmSimtSm80Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<64,64,4>,cutlass::gemm::GemmShape<32,16,4>,gemm::threadblock::ThreadblockSwizzleStreamK,4,1>();});
  // ins.add({7,(int16_t)ME::GemmNormalSimt,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm80}, /*op*/[]() { return new GemmSimtSm80Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<64,64,4>,cutlass::gemm::GemmShape<32,16,4>,gemm::threadblock::ThreadblockSwizzleStreamK,4,2>();});
  // ins.add({8,(int16_t)ME::GemmNormalSimt,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm80}, /*op*/[]() { return new GemmSimtSm80Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<32,32,4>,cutlass::gemm::GemmShape<16,16,4>,gemm::threadblock::GemmIdentityThreadblockSwizzle<>,3,1>();});
  // ins.add({9,(int16_t)ME::GemmNormalSimt,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm80}, /*op*/[]() { return new GemmSimtSm80Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<32,32,4>,cutlass::gemm::GemmShape<16,16,4>,gemm::threadblock::GemmIdentityThreadblockSwizzle<>,3,2>();});
  // ins.add({10,(int16_t)ME::GemmNormalSimt,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm80}, /*op*/[]() { return new GemmSimtSm80Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<32,32,4>,cutlass::gemm::GemmShape<16,16,4>,gemm::threadblock::GemmIdentityThreadblockSwizzle<>,4,1>();});
  // ins.add({11,(int16_t)ME::GemmNormalSimt,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm80}, /*op*/[]() { return new GemmSimtSm80Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<32,32,4>,cutlass::gemm::GemmShape<16,16,4>,gemm::threadblock::GemmIdentityThreadblockSwizzle<>,4,2>();});
  // ins.add({12,(int16_t)ME::GemmNormalSimt,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm80}, /*op*/[]() { return new GemmSimtSm80Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<32,32,4>,cutlass::gemm::GemmShape<16,16,4>,gemm::threadblock::ThreadblockSwizzleStreamK,3,1>();});
  // ins.add({13,(int16_t)ME::GemmNormalSimt,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm80}, /*op*/[]() { return new GemmSimtSm80Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<32,32,4>,cutlass::gemm::GemmShape<16,16,4>,gemm::threadblock::ThreadblockSwizzleStreamK,3,2>();});
  // ins.add({14,(int16_t)ME::GemmNormalSimt,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm80}, /*op*/[]() { return new GemmSimtSm80Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<32,32,4>,cutlass::gemm::GemmShape<16,16,4>,gemm::threadblock::ThreadblockSwizzleStreamK,4,1>();});
  // ins.add({15,(int16_t)ME::GemmNormalSimt,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm80}, /*op*/[]() { return new GemmSimtSm80Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<32,32,4>,cutlass::gemm::GemmShape<16,16,4>,gemm::threadblock::ThreadblockSwizzleStreamK,4,2>();});
  // ins.add({16,(int16_t)ME::GemmNormalSimt,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm80}, /*op*/[]() { return new GemmSimtSm80Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<16,32,4>,cutlass::gemm::GemmShape<8,16,4>,gemm::threadblock::GemmIdentityThreadblockSwizzle<>,3,1>();});
  // ins.add({17,(int16_t)ME::GemmNormalSimt,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm80}, /*op*/[]() { return new GemmSimtSm80Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<16,32,4>,cutlass::gemm::GemmShape<8,16,4>,gemm::threadblock::GemmIdentityThreadblockSwizzle<>,3,2>();});
  // ins.add({18,(int16_t)ME::GemmNormalSimt,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm80}, /*op*/[]() { return new GemmSimtSm80Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<16,32,4>,cutlass::gemm::GemmShape<8,16,4>,gemm::threadblock::GemmIdentityThreadblockSwizzle<>,4,1>();});
  // ins.add({19,(int16_t)ME::GemmNormalSimt,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm80}, /*op*/[]() { return new GemmSimtSm80Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<16,32,4>,cutlass::gemm::GemmShape<8,16,4>,gemm::threadblock::GemmIdentityThreadblockSwizzle<>,4,2>();});
  // ins.add({20,(int16_t)ME::GemmNormalSimt,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm80}, /*op*/[]() { return new GemmSimtSm80Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<16,32,4>,cutlass::gemm::GemmShape<8,16,4>,gemm::threadblock::ThreadblockSwizzleStreamK,3,1>();});
  // ins.add({21,(int16_t)ME::GemmNormalSimt,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm80}, /*op*/[]() { return new GemmSimtSm80Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<16,32,4>,cutlass::gemm::GemmShape<8,16,4>,gemm::threadblock::ThreadblockSwizzleStreamK,3,2>();});
  // ins.add({22,(int16_t)ME::GemmNormalSimt,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm80}, /*op*/[]() { return new GemmSimtSm80Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<16,32,4>,cutlass::gemm::GemmShape<8,16,4>,gemm::threadblock::ThreadblockSwizzleStreamK,4,1>();});
  // ins.add({23,(int16_t)ME::GemmNormalSimt,(int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::BF16, (int16_t)ME::FP32, (int16_t)ME::RCR, (int16_t)ME::Sm80}, /*op*/[]() { return new GemmSimtSm80Impl</*meta*/cutlass::bfloat16_t, cutlass::bfloat16_t, cutlass::bfloat16_t, float, layout::RowMajor, layout::ColumnMajor, layout::RowMajor, arch::Sm80,/*hparam*/cutlass::gemm::GemmShape<16,32,4>,cutlass::gemm::GemmShape<8,16,4>,gemm::threadblock::ThreadblockSwizzleStreamK,4,2>();});
  return 0;
}();
}
#endif // #if XOP_CUDA_ARCHSXOP_CUDA_ARCHS==80 || XOP_CUDA_ARCHS==86 || XOP_CUDA_ARCHS==89
// clang-format on